version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: guzo-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./guzo:/guzo
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    environment:
      TZ: Europe/Helsinki
  postgres:
    image: postgres
    restart: always
    container_name: guzo-postgres
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    stdin_open: true
    tty: true
    environment:
      TZ: Europe/Helsinki
  web:
    restart: always
    container_name: guzo-web
    image: guzo-web-image
    build:
      context: ./tools/web
      dockerfile: ${PWD}/Dockerfile
    volumes:
      - ./guzo:/guzo
    expose:
      - '8000'
    links:
      - postgres
      - memcache
      - redis
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && gunicorn prod.wsgi 0.0.0.0:8001'
    depends_on:
      - postgres
    extra_hosts:
      - 'www.guzo.dev:127.0.0.1'
    environment:
      VIRTUAL_HOST: www.guzo.dev
      HTTPS_METHOD: noredirect
      TZ: Europe/Helsinki
  memcache:
    image: 'memcached:latest'
    container_name: guzo-memcache
    command: memcached
    environment:
      TZ: Europe/Helsinki
  pgadmin:
    image: fenglc/pgadmin4
    container_name: guzo-pgadmin
    links:
      - 'postgres:postgres'
    ports:
      - '5050:5050'
    environment:
      TZ: Europe/Helsinki
  redis:
    restart: always
    image: 'redis:3-alpine'
    container_name: guzo-redis
    command: redis-server
    environment:
      TZ: Europe/Helsinki
volumes:
  pgdata: null
