# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 23:15
from __future__ import unicode_literals

import audit_log.models.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('entry_status', models.IntegerField(choices=[(1, 'Still draft'), (2, 'New'), (3, 'Approved'), (4, 'Published')], default=1)),
                ('slug', models.SlugField(blank=True, default=1, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gallery_type', models.IntegerField(choices=[('1', 'Facebook'), ('2', 'Twitter'), ('3', 'LinkedIn'), ('4', 'Instagram'), ('5', 'Google+'), ('6', 'Pinterest'), ('7', 'Other')], default=1)),
                ('image_data', models.ImageField(upload_to=b'gallery')),
                ('caption', models.CharField(default=b'', max_length=60)),
                ('video_url', models.CharField(blank=True, default=b'', max_length=100, validators=[django.core.validators.URLValidator()])),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lightrail_media_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_lightrail_media_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('entry_status', models.IntegerField(choices=[(1, 'Still draft'), (2, 'New'), (3, 'Approved'), (4, 'Published')], default=1)),
                ('slug', models.SlugField(blank=True, default=1, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quota_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code=b'nomatch', message=b'Length has to be 4', regex=b'^.{4}$')])),
                ('description', models.TextField(blank=True, max_length=100)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lightrail_pricequota_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_lightrail_pricequota_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('entry_status', models.IntegerField(choices=[(1, 'Still draft'), (2, 'New'), (3, 'Approved'), (4, 'Published')], default=1)),
                ('slug', models.SlugField(blank=True, default=1, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('locale', models.CharField(max_length=100)),
                ('number_of_lines', models.PositiveSmallIntegerField()),
                ('number_of_stations', models.PositiveSmallIntegerField()),
                ('transit_type', models.CharField(max_length=100)),
                ('budget', models.IntegerField(blank=True, default=0)),
                ('daily_ridership', models.IntegerField(default=0)),
                ('operation_start_date', models.DateField()),
                ('operators', models.CharField(max_length=100)),
                ('number_of_vehicles', models.PositiveSmallIntegerField()),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lightrail_service_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_lightrail_service_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'ordering': ('name', 'number_of_stations', 'number_of_lines'),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('entry_status', models.IntegerField(choices=[(1, 'Still draft'), (2, 'New'), (3, 'Approved'), (4, 'Published')], default=1)),
                ('slug', models.SlugField(blank=True, default=1, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code=b'nomatch', message=b'Length has to be 6', regex=b'^.{6}$')])),
                ('name', models.CharField(max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('place', models.IntegerField(choices=[('1', 'Addis Ababa'), ('2', 'Adama'), ('3', 'Gondar'), ('4', 'Mekele'), ('5', 'Hawassa'), ('6', 'Bahir Dar'), ('7', 'Dire Dawa'), ('8', 'Dessie'), ('9', 'Jimma'), ('10', 'Jijiga'), ('11', 'Shashamane'), ('12', 'Arba Minch'), ('13', 'Hosaena'), ('14', 'Dila'), ('15', 'Nekemte'), ('16', 'Debre Birhan'), ('17', 'Asella'), ('18', 'Harar'), ('19', 'Asmera'), ('19', 'Woliso'), ('20', 'Unspecified')], default=1)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('operational_status', models.IntegerField(choices=[('1', 'Planned'), ('2', 'Under construction'), ('3', 'Opened'), ('4', 'Under maintenance'), ('4', 'Closed')], default=1)),
                ('ticket_sale', models.BooleanField(default=True)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lightrail_station_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_lightrail_station_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
                ('service', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lightrail.Service')),
            ],
            options={
                'ordering': ('name', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_with_session_key', audit_log.models.fields.CreatingSessionKeyField(editable=False, max_length=40, null=True)),
                ('modified_with_session_key', audit_log.models.fields.LastSessionKeyField(editable=False, max_length=40, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('entry_status', models.IntegerField(choices=[(1, 'Still draft'), (2, 'New'), (3, 'Approved'), (4, 'Published')], default=1)),
                ('slug', models.SlugField(blank=True, default=1, max_length=100, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('system_length', models.CharField(max_length=100)),
                ('track_gauge', models.CharField(max_length=100)),
                ('top_speed', models.CharField(max_length=100)),
                ('electrification', models.CharField(max_length=100)),
                ('created_by', audit_log.models.fields.CreatingUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_lightrail_technical_set', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('modified_by', audit_log.models.fields.LastUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_lightrail_technical_set', to=settings.AUTH_USER_MODEL, verbose_name='modified by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='service',
            name='technical',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightrail.Technical'),
        ),
        migrations.AddField(
            model_name='media',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightrail.Service'),
        ),
        migrations.AddField(
            model_name='media',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lightrail.Station'),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set([('code',)]),
        ),
        migrations.AlterUniqueTogether(
            name='pricequota',
            unique_together=set([('quota_code',)]),
        ),
    ]
