# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-12 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, default=8, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricequota',
            name='slug',
            field=models.SlugField(blank=True, default=8, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default=8, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, default=8, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='slug',
            field=models.SlugField(blank=True, default=8, max_length=100, null=True),
        ),
    ]
