# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightrail', '0002_auto_20180512_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='gallery_type',
            field=models.IntegerField(choices=[(1, 'Facebook'), (2, 'Twitter'), (3, 'LinkedIn'), (4, 'Instagram'), (5, 'Google+'), (6, 'Pinterest'), (7, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricequota',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='operational_status',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Under construction'), (3, 'Opened'), (4, 'Under maintenance'), (4, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='station',
            name='place',
            field=models.IntegerField(choices=[(1, 'Addis Ababa'), (2, 'Adama'), (3, 'Gondar'), (4, 'Mekele'), (5, 'Hawassa'), (6, 'Bahir Dar'), (7, 'Dire Dawa'), (8, 'Dessie'), (9, 'Jimma'), (10, 'Jijiga'), (11, 'Shashamane'), (12, 'Arba Minch'), (13, 'Hosaena'), (14, 'Dila'), (15, 'Nekemte'), (16, 'Debre Birhan'), (17, 'Asella'), (18, 'Harar'), (19, 'Asmera'), (19, 'Woliso'), (20, 'Unspecified')], default=1),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=100, null=True),
        ),
    ]
