# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guzo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overviewmetadata',
            old_name='native_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='station',
            name='street_name',
            field=models.CharField(blank=True, default=b'AA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overviewmetadata',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='long',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='system_length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technical',
            name='top_speed',
            field=models.CharField(max_length=100),
        ),
    ]
