# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guzo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image_data',
            field=models.ImageField(upload_to=b'gallery'),
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='slug',
            field=models.SlugField(blank=True, default=1, max_length=100, null=True),
        ),
    ]
