# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guzo', '0002_auto_20171121_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='ticket_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, default=6, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default=6, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, default=6, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='slug',
            field=models.SlugField(blank=True, default=6, max_length=100, null=True),
        ),
    ]
