# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guzo', '0003_auto_20171121_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guzo.Service'),
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, default=3, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, default=3, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, default=3, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='slug',
            field=models.SlugField(blank=True, default=3, max_length=100, null=True),
        ),
    ]
