# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guzo', '0003_auto_20171118_2335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='street_name',
            new_name='street_address',
        ),
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overviewmetadata',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='slug',
            field=models.SlugField(blank=True, default=2, max_length=100, null=True),
        ),
    ]
