# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guzo', '0004_auto_20171118_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='slug',
            field=models.SlugField(blank=True, default=4, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overviewmetadata',
            name='budget',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='overviewmetadata',
            name='slug',
            field=models.SlugField(blank=True, default=4, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='long',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(blank=True, default=4, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical',
            name='slug',
            field=models.SlugField(blank=True, default=4, max_length=100, null=True),
        ),
    ]
